In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
import json
import gmaps
import os
from scipy.stats import linregress
from config import api_key
from config import g_key

Store Part I results into DataFrame

Load the csv exported in Part I to a DataFrame

In [6]:
# Loan CSV file generated from WeatherPy Folder
weather_data_to_load = "../WeatherPy/output_data/cities.csv"
weather_data = pd.read_csv(weather_data_to_load)
dropna_weather_data.head(20)

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,Unnamed: 0.1.1.1.1.1,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,0,0,0,0,0,punta arenas,90,PH,1579714331,92,8.99,125.34,72.72,1.41
1,1,1,1,1,1,1,rikitea,0,PF,1579714332,80,-23.12,-134.97,78.06,12.53
2,2,2,2,2,2,2,atuona,33,PF,1579714332,75,-9.80,-139.03,80.82,13.38
3,3,3,3,3,3,3,skibbereen,75,IE,1579714108,87,51.55,-9.27,50.00,4.70
4,4,4,4,4,4,4,mwense,100,ZM,1579714332,98,-10.38,28.70,67.77,2.26
5,5,5,5,5,5,5,nikolskoye,75,RU,1579714333,61,59.70,30.79,32.00,15.66
6,6,6,6,6,6,6,avarua,100,CK,1579714333,88,-21.21,-159.78,80.60,11.41
7,7,7,7,7,7,7,jamestown,1,US,1579714333,62,42.10,-79.24,30.99,8.05
8,8,8,8,8,8,8,tuktoyaktuk,90,CA,1579714333,75,69.45,-133.04,-14.80,9.17
9,9,9,9,9,9,9,awbari,0,LY,1579714333,32,26.59,12.78,57.87,8.99
10,10,10,10,10,10,10,port-gentil,40,GA,1579714333,79,-0.72,8.78,86.00,8.05
11,11,11,11,11,11,11,longyearbyen,0,SJ,1579714107,77,78.22,15.64,-2.20,3.36
12,12,12,12,12,12,12,itoman,75,JP,1579714333,77,26.12,127.67,66.20,4.70
13,13,13,13,13,13,13,mataura,57,NZ,1579714334,88,-46.19,168.86,57.00,11.01
14,14,14,14,14,14,14,bluff,83,NZ,1579714334,88,-46.60,168.33,57.00,11.01
15,15,15,15,15,15,15,qaanaaq,1,GL,1579714334,51,77.48,-69.36,-11.87,7.61
16,16,16,16,16,16,16,ushuaia,75,AR,1579714099,54,-54.80,-68.30,53.60,6.93
17,17,17,17,17,17,17,hobart,90,AU,1579714334,93,-42.88,147.33,57.20,5.82
18,18,18,18,18,18,18,hilo,75,US,1579714334,64,19.73,-155.09,68.00,6.93
19,19,19,19,19,19,19,pisco,90,PE,1579714122,30,-13.70,-76.22,73.99,6.93

In [ ]:
 Humidity Heatmap

Configure gmaps.
Use the Lat and Lng as locations and Humidity as the weight.
Add Heatmap layer to map.

In [ ]:
 Create new DataFrame fitting weather criteria

Narrow down the cities to fit weather conditions.
Drop any rows will null values.

In [ ]:
 Hotel Map

Store into variable named hotel_df.
Add a "Hotel Name" column to the DataFrame.
Set parameters to search for hotels with 5000 meters.
Hit the Google Places API for each city's coordinates.
Store the first Hotel result into the DataFrame.
Plot markers on top of the heatmap.

In [ ]:
 # NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display Map